routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::name('add')->get('add', function(){
	return view('add');
	Route::resource( [
        
        'parameters' => ['profile' => 'user']
    ]);
	
});

Route::name('locations')->get('locations', function(){
	$data = [
		'points'=>App\Point::all()
	];
	return view('locations', $data);
});

Route::post('add', function(){
	$rules = [
		'address'=>'required'
	];

	$validation = Validator::make(Request::all(), $rules);
	if($validation->fails()){
		return back()->withErrors($validation)->withInput();
	}

	$param = array('address'=>Request::input('address'));
	$response = \Geocoder::geocode('json', $param);
	$location = json_decode($response);

	//dd($location);

	if($location->status == 'OK'){
		$name = $location->results[0]->address_components[0]->long_name;
		$address = $location->results[0]->formatted_address;
		$lat = $location->results[0]->geometry->location->lat;
		$lng = $location->results[0]->geometry->location->lng;

		if($lat && $lng){
			$point = new App\Point;
			$point->name = $name;
			$point->address = $address;
			$point->lat = $lat;
			$point->lng = $lng;
			$point->user_id = \Auth::user()->id;

			if($point->save()){
				return back()->withSuccess('Adresse ajoutée');
			}
		}
	}
	else{
		dd($location);
	}
});

Route::middleware('admin')->group(function () {
    Route::resource ('category', 'CategoryController', [
        'except' => 'show'
    ]);
    Route::name('maintenance.index')->get('maintenance', 'AdminController@index');
    Route::name('maintenance.destroy')->delete('maintenance', 'AdminController@destroy');
});

Route::middleware('auth')->group(function () {
	
    Route::resource('image', 'ImageController', [
		'only' => ['create', 'store', 'destroy','update']
		
		
    ]);
    Route::resource('profile', 'UserController', [
        'only' => ['edit', 'update'],
        'parameters' => ['profile' => 'user']
    ]);
});

Route::name('category')->get('category/{slug}', 'ImageController@category');

Route::name('user')->get('user/{user}', 'ImageController@user');

resources/views/add.blade.php
<!DOCTYPE html>
    <html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'Where are the graffs') }}</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        @yield('css')
        <link href="{{ asset('css/add.css') }}" rel="stylesheet">
    @yield('css')
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    </head>
    <body>
    
   
    
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ route('home') }}">{{ config('app.name', 'Album') }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle
        @isset($category)
            {{ currentRoute(route('category', $category->slug)) }}
        @endisset
            " href="#" id="navbarDropdownCat" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @lang('Catégories')
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownCat">
        @foreach($categories as $category)
            <a class="dropdown-item" href="{{ route('category', $category->slug) }}">{{ $category->name }}</a>
        @endforeach
    </div>
</li>

            @admin
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle{{ currentRoute(
                route('category.create'),
                route('category.index'),
                route('category.edit', request()->category?:0)
            )}}" href="#" id="navbarDropdownGestCat" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @lang('Administration')
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownGestCat">
            <a class="dropdown-item" href="{{ route('category.create') }}">
                <i class="fas fa-plus fa-lg"></i> @lang('Ajouter une catégorie')
            </a>
            <a class="dropdown-item" href="{{ route('category.index') }}">
                <i class="fas fa-wrench fa-lg"></i> @lang('Gérer les catégories')
            </a>
            <a class="dropdown-item" href="{{ route('maintenance.index') }}">
                <i class="fas fa-cogs fa-lg"></i> @lang('Maintenance')
            </a>
        </div>
    </li>
    @endadmin
                @auth
                    <li class="nav-item{{ currentRoute(route('image.create')) }}"><a class="nav-link" href="{{ route('image.create') }}">@lang('Ajouter une image')</a></li>
                @endauth
                <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle
            )}}" href="#" id="navbarDropdownGestCat" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @lang('Carte')
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownGestCat">
            <a class="dropdown-item" href="{{ route('add') }}">
                <i class="fas fa-plus fa-lg"></i> @lang('Ajouter une oeuvre')
            </a>
            <a class="dropdown-item" href="{{ route('locations') }}">
                <i class="fas fa-wrench fa-lg"></i> @lang('Voir la carte des oeuvres')
            </a>
            
        </div>
    </li>

               
               
            </ul>
            <ul class="navbar-nav ml-auto">
                @guest
                    <li class="nav-item{{ currentRoute(route('login')) }}"><a class="nav-link" href="{{ route('login') }}">@lang('Connexion')</a></li>
                    <li class="nav-item{{ currentRoute(route('register')) }}"><a class="nav-link" href="{{ route('register') }}">@lang('Inscription')</a></li>
                    @else
                    <li class="nav-item{{ currentRoute(route('profile.edit', auth()->id())) }}"><a class="nav-link" href="{{ route('profile.edit', auth()->id()) }}">@lang('Profil')</a></li>
                    <li class="nav-item">
                        <a id="logout" class="nav-link" href="{{ route('logout') }}">@lang('Déconnexion')</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hide">
                            {{ csrf_field() }}
                        </form>
                    </li>
                @endguest
            </ul>
        </div>
    </nav>

    @if (session('ok'))
        <div class="container">
            <div class="alert alert-dismissible alert-success fade show" role="alert">
                {{ session('ok') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    @endif

    @yield('content')

@extends('layout')


@section('content')

<div class="container center">

@if(Session::has('success'))

    <div class="alert alert-success">{{Session::get('success')}}</div>

@endif

<form action="{{url('add')}}" method="post">
{{csrf_field()}}
    <div class="form-group">
        <label for="address">Entrez la rue où se trouve l'oeuvre</label>
        <input type="text" class="form-control" name="address" id="address" placeholder="Adresse">
        @if($errors->has('address'))
        <span class="label label-danger">{{$errors->first('address')}}</span>
        @endif
    </div>

    <div class="form-group">
    <input type="submit" class="btn btn-primary" value="Envoyer">
    </div>
</form>

</div>

@stop
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

    <main class="container-fluid">
        @isset($category)
            <h2 class="text-title mb-3">{{ $category->name }}</h2>
        @endif
        @isset($user)
            <h2 class="text-title mb-3">{{ __('Photos de ') . $user->name }}</h2>
        @endif
        <div class="card-columns">
            @foreach($images as $image)
                <div class="card">
                    <a href="{{ asset('images/' . $image->name) }}" class="image-link"><img class="card-img-top" src="{{ asset('thumbs/' . $image->name) }}" alt="image"></a>
                    @isset($image->description)
                        <div class="card-body">
                            <p class="card-text">{{ $image->description }}</p>
                        </div>
                    @endisset
                    <div class="card-footer text-muted">
                        <small><em>
                                    <a href="{{ route('user', $image->user->id) }}" data-toggle="tooltip" title="{{ __('Voir les photos de ') . $image->user->name }}">{{ $image->user->name }}</a>
                            </em></small>
                        <small class="pull-right">
                            <em>
                            {{ $image->created_at->formatLocalized('%x') }}
                                @adminOrOwner($image->user_id)
                                
                            

                                <a class="category-edit" id="{{$image->category_id}}" href="{{ route('image.update', ['id' => $image->id] ) }}" data-toggle="tooltip" title="@lang('Changer de catégorie')"><i class="fa fa-edit"></i></a>
                                <div class="modal fade" id="changeCategory" tabindex="-1" role="dialog" aria-labelledby="categoryLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="categoryLabel">@lang('Changement de la catégorie')</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                <form action="" method="POST">
        <input type="hidden" name="_method" value="PUT">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                   
                        <div class="form-group">
                            <select class="form-control" name="category_id">
                            @foreach($categories as $cat)
                                <option value="{{ $cat->id }}">{{ $cat->name }}</option>
                            @endforeach
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">@lang('Envoyer')</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <a class="form-delete" href="{{ route('image.destroy', $image->id) }}" data-toggle="tooltip" title="@lang('Supprimer cette photo')"><i class="fa fa-trash"></i></a>
                                
                                <form action="{{ route('image.destroy', $image->id) }}" method="POST" class="hide">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>
                                @endadminOrOwner
                            </em>
                        </small>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="d-flex justify-content-center">
            {{ $images->links() }}
        </div>
    </main>
    
@endsection

@section('script')
    <script>
        $(function() {
            $('[data-toggle="tooltip"]').tooltip()

            $('.card-columns').magnificPopup({
                delegate: 'a.image-link',
                type: 'image',
                gallery: { enabled: true }
            });

            $('a.form-delete').click(function(e) {
                e.preventDefault();
                let href = $(this).attr('href')
                $("form[action='" + href + "'").submit()
            })
        })
        $('.category-edit').click(function (e) {
        e.preventDefault()
        $('#changeCategory').modal('show')
    })
    $('.category-edit').click(function (e) {
        e.preventDefault()
        $('select').val($(this).attr('id'))
        $('#changeCategory').modal('show')
    })
    $('a.category-edit').click(function (e) {
        e.preventDefault()
        $('select').val($(this).attr('id'))
        console.log("$(this).next().attr('href')", $(this).attr('href'));
        $('form').attr('action', $(this).attr('href'))
        $('#changeCategory').modal('show')
    })
    </script>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Title Page</title>

        <!-- Bootstrap CSS -->
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <style>
        body{
            padding-top: 50px;
        }
        #map{
            width: 100%;
            height: 500px;
            color:red;
       
        }
        </style>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
    

        @yield('content')

        <!-- jQuery -->
        <script src="//code.jquery.com/jquery.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

         <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDE24Sg4vYQzgP4y_Fq0fMw1iG_en6dgnU&signed_in=true&libraries=places"></script> 


        <script src="{{asset('js/jquery.geocomplete.js')}}"></script>

        <script> $('#address').geocomplete();</script>

        <script>

        </script>

        @if(Request::is('locations'))

            <script>
            var myLatLng = {lat: {{$points[0]->lat}}, lng: {{$points[0]->lng}}};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: myLatLng
                
                
            });

            @if($points)
                @foreach($points as $point)
                    var marker{{$point->id}} = new google.maps.Marker({
                        position: new google.maps.LatLng({{$point->lat}}, {{$point->lng}}),
                        map: map,
                        title: '{{$point->name}}'
                        
                    });
                    
                @endforeach
            @endif

            </script>

        @endif
    </body>
</html>

resources/views/locations.blade.php
<!DOCTYPE html>
    <html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'Where are the graffs') }}</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        @yield('css')
        <link href="{{ asset('css/add.css') }}" rel="stylesheet">
        @yield('css')
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    </head>
    <body>
    
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        
        <a  class="navbar-brand" href="{{ route('home') }}"><img src="{!! asset('/images/lyon.png') !!}" width="45%">{{ config('app.name', 'Album') }} </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle
        @isset($category)
            {{ currentRoute(route('category', $category->slug)) }}
        @endisset
            " href="#" id="navbarDropdownCat" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @lang('Oeuvres par catégories')
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownCat">
        @foreach($categories as $category)
            <a class="dropdown-item" href="{{ route('category', $category->slug) }}">{{ $category->name }}</a>
        @endforeach
    </div>
</li>

            @admin
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle{{ currentRoute(
                route('category.create'),
                route('category.index'),
                route('category.edit', request()->category?:0)
            )}}" href="#" id="navbarDropdownGestCat" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @lang('Administration')
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownGestCat">
            <a class="dropdown-item" href="{{ route('category.create') }}">
                <i class="fas fa-plus fa-lg"></i> @lang('Ajouter une catégorie')
            </a>
            <a class="dropdown-item" href="{{ route('category.index') }}">
                <i class="fas fa-wrench fa-lg"></i> @lang('Gérer les catégories')
            </a>
            <a class="dropdown-item" href="{{ route('maintenance.index') }}">
                <i class="fas fa-cogs fa-lg"></i> @lang('Maintenance')
            </a>
        </div>
    </li>
    @endadmin
                @auth
                    <li class="nav-item{{ currentRoute(route('image.create')) }}"><a class="nav-link" href="{{ route('image.create') }}">@lang('Ajouter une oeuvre')</a></li>
                @endauth
                @auth
                    <li class="nav-item{{ currentRoute(route('locations')) }}"><a class="nav-link"href="{{ route('locations') }}">@lang('Carte des oeuvres')</a></li>
                @endauth
              
    </li>

               
               
            </ul>
            <ul class="navbar-nav ml-auto">
                @guest
                    <li class="nav-item{{ currentRoute(route('login')) }}"><a class="nav-link" href="{{ route('login') }}">@lang('Connexion')</a></li>
                    <li class="nav-item{{ currentRoute(route('register')) }}"><a class="nav-link" href="{{ route('register') }}">@lang('Inscription')</a></li>
                    @else
                    <li class="nav-item{{ currentRoute(route('profile.edit', auth()->id())) }}"><a class="nav-link" href="{{ route('profile.edit', auth()->id()) }}">@lang('Profil')</a></li>
                    <li class="nav-item">
                        <a id="logout" class="nav-link" href="{{ route('logout') }}">@lang('Déconnexion')</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hide">
                            {{ csrf_field() }}
                        </form>
                    </li>
                @endguest
            </ul>
        </div>
    </nav>

    @if (session('ok'))
        <div class="container">
            <div class="alert alert-dismissible alert-success fade show" role="alert">
                {{ session('ok') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    @endif

    @yield('content')

@extends('layout')


@section('content')

<div class="container center">

@if(Session::has('success'))

    <div class="alert alert-success">{{Session::get('success')}}</div>

@endif
@extends('layout')


@section('content')

<div class="container center">

<div id="map"></div>

@if(isset($points))
    @foreach($points as $point)
         <p><strong>{{$point->name}}</strong> : {{$point->address}}</p> 
    @endforeach
@endif

</div>

@stop
</body>
</html>