routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::name('add')->get('add', function(){
	return view('add');
	Route::resource( [
        
        'parameters' => ['profile' => 'user']
    ]);
	
});

Route::name('locations')->get('locations', function(){
	$data = [
		'points'=>App\Point::all()
	];
	return view('locations', $data);
});

Route::post('add', function(){
	$rules = [
		'address'=>'required'
	];

	$validation = Validator::make(Request::all(), $rules);
	if($validation->fails()){
		return back()->withErrors($validation)->withInput();
	}

	$param = array('address'=>Request::input('address'));
	$response = \Geocoder::geocode('json', $param);
	$location = json_decode($response);

	//dd($location);

	if($location->status == 'OK'){
		$name = $location->results[0]->address_components[0]->long_name;
		$address = $location->results[0]->formatted_address;
		$lat = $location->results[0]->geometry->location->lat;
		$lng = $location->results[0]->geometry->location->lng;

		if($lat && $lng){
			$point = new App\Point;
			$point->name = $name;
			$point->address = $address;
			$point->lat = $lat;
			$point->lng = $lng;
			$point->user_id = \Auth::user()->id;

			if($point->save()){
				return back()->withSuccess('Adresse ajoutée');
			}
		}
	}
	else{
		dd($location);
	}
});

Route::middleware('admin')->group(function () {
    Route::resource ('category', 'CategoryController', [
        'except' => 'show'
    ]);
    Route::name('maintenance.index')->get('maintenance', 'AdminController@index');
    Route::name('maintenance.destroy')->delete('maintenance', 'AdminController@destroy');
});

Route::middleware('auth')->group(function () {
	
    Route::resource('image', 'ImageController', [
		'only' => ['create', 'store', 'destroy','update']
		
		
    ]);
    Route::resource('profile', 'UserController', [
        'only' => ['edit', 'update'],
        'parameters' => ['profile' => 'user']
    ]);
});

Route::name('category')->get('category/{slug}', 'ImageController@category');

Route::name('user')->get('user/{user}', 'ImageController@user');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'settings',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

public function images()
{
    return $this->hasMany(Image::class);
}
public function points()
{
    return $this->hasMany(Points::class);
}

}

app/Http/Controllers/UserController.php
<?php
    namespace App\Http\Controllers;
    use Illuminate\Http\Request;
    use App\Models\User;
    class UserController extends Controller
    {
        public function edit(User $user)
        {
            $settings = json_decode($user->settings);
            return view ('users.edit', compact('user', 'settings'));
        }
        public function update(Request $request, User $user)
        {
            $this->authorize('update', $user);
            
            $request->validate([
                'email' => 'required|string|email|max:255|unique:users,email,' . $user->id,
                'pagination' => 'required',
            ]);
            $user->update([
                'email' => $request->email,
                'settings' => json_encode(['pagination' => $request->pagination]),
            ]);
            return back()->with(['ok' => __('Le profil a bien été mis à jour')]);
        }
    }

resources/views/users/edit.blade.php
@extends('layouts.form')
    @section('css')
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/css/bootstrap-slider.min.css">
    @endsection
    @section('card')
        @component('components.card')
            @slot('title')
                @lang('Modifer le profil')
            @endslot
            <form method="POST" action="{{ route('profile.update', $user->id) }}">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                @include('partials.form-group', [
                    'title' => __('Adresse email'),
                    'type' => 'email',
                    'name' => 'email',
                    'required' => true,
                    'value' => $user->email,
                    ])
                <div class="form-group">
                    @lang('Pagination : ')<span id="nbr">{{ $settings->pagination }}</span> @lang('images par page')<br>
                    <input id="pagination" name="pagination" type="number" data-slider-min="3" data-slider-max="20" data-slider-step="1" data-slider-value="{{ $settings->pagination }}"/><br>                
                </div>
                @component('components.button')
                    @lang('Envoyer')
                @endcomponent
            </form> 
        @endcomponent            
    @endsection
    @section('script')
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.9.0/bootstrap-slider.min.js"></script>
        <script>
            $(function() {
                $("#pagination")
                .slider()
                .on("slide", function(e) {
                    $("#nbr").text(e.value)
                })
                .on("change", function(e) {
                    $("#nbr").text(e.value.newValue)
                })
            })
        </script>
    @endsection