routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::name('add')->get('add', function(){
	return view('add');
	Route::resource( [
        
        'parameters' => ['profile' => 'user']
    ]);
	
});

Route::name('locations')->get('locations', function(){
	$data = [
		'points'=>App\Point::all()
	];
	return view('locations', $data);
});

Route::post('add', function(){
	$rules = [
		'address'=>'required'
	];

	$validation = Validator::make(Request::all(), $rules);
	if($validation->fails()){
		return back()->withErrors($validation)->withInput();
	}

	$param = array('address'=>Request::input('address'));
	$response = \Geocoder::geocode('json', $param);
	$location = json_decode($response);

	//dd($location);

	if($location->status == 'OK'){
		$name = $location->results[0]->address_components[0]->long_name;
		$address = $location->results[0]->formatted_address;
		$lat = $location->results[0]->geometry->location->lat;
		$lng = $location->results[0]->geometry->location->lng;

		if($lat && $lng){
			$point = new App\Point;
			$point->name = $name;
			$point->address = $address;
			$point->lat = $lat;
			$point->lng = $lng;
			$point->user_id = \Auth::user()->id;

			if($point->save()){
				return back()->withSuccess('Adresse ajoutée');
			}
		}
	}
	else{
		dd($location);
	}
});

Route::middleware('admin')->group(function () {
    Route::resource ('category', 'CategoryController', [
        'except' => 'show'
    ]);
    Route::name('maintenance.index')->get('maintenance', 'AdminController@index');
    Route::name('maintenance.destroy')->delete('maintenance', 'AdminController@destroy');
});

Route::middleware('auth')->group(function () {
	
    Route::resource('image', 'ImageController', [
		'only' => ['create', 'store', 'destroy','update']
		
		
    ]);
    Route::resource('profile', 'UserController', [
        'only' => ['edit', 'update'],
        'parameters' => ['profile' => 'user']
    ]);
});

Route::name('category')->get('category/{slug}', 'ImageController@category');

Route::name('user')->get('user/{user}', 'ImageController@user');

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\ { User, Category };

class Image extends Model
{
    /**
     * Get the category that owns the image.
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get the user that owns the image.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Scope a query eager load user and order query.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeLatestWithUser($query)
    {
        return $query->with('user')->latest();
    }
   

}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ { User, Image, Category };
use App\Repositories\ImageRepository;
use Validator;


class ImageController extends Controller
{
    protected $repository;

    /**
     * Create a new ImageController instance.
     *
     * @param  \App\Repositories\ImageRepository $repository
     */
    public function __construct(ImageRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('images.create');
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Image $image)
    {
        $image->category_id = $request->category_id;
        $image->save();
        return redirect()->back();
    }

    public function store(Request $request)
    {
        $request->validate([
            'image' => 'required|image|max:2000',
            'category_id' => 'required|exists:categories,id',
            'description' => 'nullable|string|max:255',
        ]);

        $this->repository->store($request);

        $rules = [
            'address'=>'required'
        ];
    
        $validation = Validator::make($request->all(), $rules);
        if($validation->fails()){
            return back()->withErrors($validation)->withInput();
        }
    
        $param = array('address'=>$request->get('address'));
        $response = \Geocoder::geocode('json', $param);
        $location = json_decode($response);
    
        //dd($location);
    
        if($location->status == 'OK'){
            $name = $location->results[0]->address_components[0]->long_name;
            $address = $location->results[0]->formatted_address;
            $lat = $location->results[0]->geometry->location->lat;
            $lng = $location->results[0]->geometry->location->lng;
    
            if($lat && $lng){
                $point = new \App\Point;
                $point->name = $name;
                $point->address = $address;
                $point->lat = $lat;
                $point->lng = $lng;
                $point->user_id = \Auth::user()->id;
    
                if($point->save()){
                    return back()->withSuccess('Adresse ajoutée');
                }
            }
        }
        else{
            dd($location);
        }

        return back()->with('ok', __("L'image a bien été enregistrée"));
    }

    /**
     * Display a listing of the images for the specified category.
     *
     * @param  string  $slug
     * @return \Illuminate\Http\Response
     */
    public function category($slug)
{
    $category = Category::whereSlug($slug)->firstorFail();
    $images = $this->repository->getImagesForCategory($slug);
    return view('home', compact('category', 'images'));
}
public function user(User $user)
{
    $images = $this->repository->getImagesForUser($user->id);
    return view('home', compact('user', 'images'));
}
public function destroy(Image $image)
{
    $this->authorize('delete', $image);
    $image->delete();
    return back();
}

}

resources/views/images/create.blade.php
@extends('layouts.form')

@section('card')

    @component('components.card')

        @slot('title')
            @lang('Ajouter une image')
        @endslot

        <form method="POST" action="{{ route('image.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('image') ? ' is-invalid' : '' }}">        
                <div class="custom-file">
                    <input type="file" id="image" name="image" class="{{ $errors->has('image') ? ' is-invalid ' : '' }}custom-file-input" required>
                    <label class="custom-file-label" for="image"></label>
                    @if ($errors->has('image'))
                        <div class="invalid-feedback">
                            {{ $errors->first('image') }}
                        </div>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <label for="category_id">@lang('Catégorie')</label>
                <select id="category_id" name="category_id" class="form-control">
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
                <div class="form-group">
        <label for="address">Entrez la rue où se trouve l'oeuvre</label>
        <input type="text" class="form-control" name="address" id="address" placeholder="Adresse">
        @if($errors->has('address'))
        <span class="label label-danger">{{$errors->first('address')}}</span>
        @endif
    </div>

    
            </div>

            @include('partials.form-group', [
                'title' => __('Description (optionnelle)'),
                'type' => 'text',
                'name' => 'description',
                'required' => false,
                ])   

            @component('components.button')
                @lang('Envoyer')
            @endcomponent

        </form>

    @endcomponent            

@endsection

@section('script')

    <script>
        $(function() {
            $('input[type="file"]').on('change',function(){
              let fileName = $(this).val().replace(/^.*[\\\/]/, '')
              $(this).next('.form-control-file').html(fileName)
            })
        })
    </script>

@endsection